// NotebookDocV2 — the P9 site document. The v1 notebook doc (version: 1) is the
// legacy shape validated by src/notebook/doc/validate.ts; THIS is what the P9
// migration produces and what the site/admin speak after the cutover.
//
// Layering (ENGINE_V2 §2, amended): pages/panels/cover/boxes are RENDER-LAYER
// content — the engine reads only panel GEOMETRY (x/y/w/h/anchor, via the
// world adapter); boxes/sketch/cover pass through untouched and unvalidated
// beyond structural sanity. Engine content (rigs/characters/poses/clips/
// behaviors) lives in registries keyed by id, each validated by its own
// schema validator. Panel hooks reference behaviors BY ID:
//   arrival — behavior run when Dash arrives at the panel (replaces v1 ArrivalDoc;
//             the migration generates `arrival:<page>:<panel>` docs).
//   travel  — weighted behavior pool for leaving the panel (replaces v1
//             TravelConfig; `when` gates live on the behavior docs themselves).
//
// Closed top level: unknown keys reject (P6b/P8 discipline).

import type { Issues } from './validate'
import { isArr, isNum, isRecord, isStr, tryValidate } from './validate'
import { tryValidateRig } from './rig'
import { tryValidateCharacter } from './character'
import { tryValidatePose } from './pose'
import { tryValidateClip } from './clip'
import { tryValidateBehavior } from './behavior'
import type { BehaviorDoc, CharacterDoc, Clip, Pose, RigTemplate } from './index'

export interface PanelV2 {
  x: number
  y: number
  w: number
  h: number
  anchor: { dx: number; dy: number }
  /** Render-layer passthrough (whiteboard boxes, sketch variant, rotation). */
  rotate?: number
  sketch?: string
  boxes?: unknown[]
  /** Behavior id run on arrival (generated by the migration from v1 ArrivalDoc). */
  arrival?: { behaviorId: string }
  /** Weighted behavior pool for onward travel (v1 TravelConfig successor). */
  travel?: { pool: { behaviorId: string; weight?: number }[] }
}

export interface PageV2 {
  name?: string
  panels: PanelV2[]
}

export interface NotebookDocV2 {
  schemaVersion: 2
  seed: number
  /** Render-layer passthrough (the cover art/copy — engine never reads it). */
  cover: unknown
  pages: PageV2[]
  rigs: Record<string, RigTemplate>
  characters: Record<string, CharacterDoc>
  poses: Record<string, Pose>
  clips: Record<string, Clip>
  behaviors: Record<string, BehaviorDoc>
}

const TOP_KEYS = new Set(['schemaVersion', 'seed', 'cover', 'pages', 'rigs', 'characters', 'poses', 'clips', 'behaviors'])
const PANEL_KEYS = new Set(['x', 'y', 'w', 'h', 'anchor', 'rotate', 'sketch', 'boxes', 'arrival', 'travel'])

function checkPanel(x: unknown, path: string, issues: Issues, behaviorIds: Set<string>): void {
  if (!isRecord(x)) {
    issues.push(`${path}: must be an object`)
    return
  }
  for (const k of Object.keys(x)) if (!PANEL_KEYS.has(k)) issues.push(`${path}.${k}: unknown field (closed schema)`)
  for (const k of ['x', 'y', 'w', 'h'] as const) {
    if (!isNum(x[k])) issues.push(`${path}.${k}: required number`)
  }
  if (isNum(x.w) && x.w <= 0) issues.push(`${path}.w: must be positive`)
  if (isNum(x.h) && x.h <= 0) issues.push(`${path}.h: must be positive`)
  if (!isRecord(x.anchor) || !isNum(x.anchor.dx) || !isNum(x.anchor.dy)) {
    issues.push(`${path}.anchor: required {dx, dy}`)
  }
  if (x.rotate !== undefined && !isNum(x.rotate)) issues.push(`${path}.rotate: must be a number`)
  if (x.sketch !== undefined && !isStr(x.sketch)) issues.push(`${path}.sketch: must be a string`)
  if (x.boxes !== undefined && !isArr(x.boxes)) issues.push(`${path}.boxes: must be an array (render payload)`)
  if (x.arrival !== undefined) {
    if (!isRecord(x.arrival) || !isStr(x.arrival.behaviorId)) issues.push(`${path}.arrival: must be { behaviorId }`)
    else if (!behaviorIds.has(x.arrival.behaviorId)) {
      issues.push(`${path}.arrival.behaviorId: references unknown behavior ${JSON.stringify(x.arrival.behaviorId)}`)
    }
  }
  if (x.travel !== undefined) {
    if (!isRecord(x.travel) || !isArr(x.travel.pool)) issues.push(`${path}.travel: must be { pool: [...] }`)
    else
      x.travel.pool.forEach((e, i) => {
        if (!isRecord(e) || !isStr(e.behaviorId)) issues.push(`${path}.travel.pool[${i}]: must be { behaviorId, weight? }`)
        else {
          if (!behaviorIds.has(e.behaviorId)) {
            issues.push(`${path}.travel.pool[${i}].behaviorId: references unknown behavior ${JSON.stringify(e.behaviorId)}`)
          }
          if (e.weight !== undefined && (!isNum(e.weight) || e.weight <= 0)) {
            issues.push(`${path}.travel.pool[${i}].weight: must be a positive number`)
          }
        }
      })
  }
}

function checkRegistry<T>(
  x: unknown,
  path: string,
  issues: Issues,
  validateOne: (doc: unknown) => { ok: boolean; errors?: string[] },
): void {
  if (!isRecord(x)) {
    issues.push(`${path}: must be an object (id → doc)`)
    return
  }
  for (const [id, doc] of Object.entries(x)) {
    const r = validateOne(doc)
    if (!r.ok) for (const e of r.errors ?? []) issues.push(`${path}.${id}: ${e}`)
    if (isRecord(doc) && isStr(doc.id) && doc.id !== id) {
      issues.push(`${path}.${id}: doc id ${JSON.stringify(doc.id)} must match its registry key`)
    }
  }
}

export function tryValidateNotebookV2(
  x: unknown,
): { ok: true; doc: NotebookDocV2 } | { ok: false; errors: string[] } {
  return tryValidate<NotebookDocV2>(x, [
    (doc, issues) => {
      if (!isRecord(doc)) {
        issues.push('doc: must be an object')
        return
      }
      for (const k of Object.keys(doc)) if (!TOP_KEYS.has(k)) issues.push(`doc.${k}: unknown field (closed schema)`)
      if (doc.schemaVersion !== 2) issues.push('schemaVersion: must be 2')
      if (!isNum(doc.seed)) issues.push('seed: required number')
      if (doc.cover === undefined) issues.push('cover: required (render payload)')

      const behaviorIds = new Set<string>(isRecord(doc.behaviors) ? Object.keys(doc.behaviors) : [])
      if (!isArr(doc.pages) || doc.pages.length === 0) issues.push('pages: required non-empty array')
      else
        doc.pages.forEach((pg, p) => {
          if (!isRecord(pg) || !isArr(pg.panels)) {
            issues.push(`pages[${p}]: must be { name?, panels: [...] }`)
            return
          }
          if (pg.name !== undefined && !isStr(pg.name)) issues.push(`pages[${p}].name: must be a string`)
          pg.panels.forEach((pn, i) => checkPanel(pn, `pages[${p}].panels[${i}]`, issues, behaviorIds))
        })

      checkRegistry(doc.rigs, 'rigs', issues, tryValidateRig)
      checkRegistry(doc.characters, 'characters', issues, tryValidateCharacter)
      checkRegistry(doc.poses, 'poses', issues, tryValidatePose)
      checkRegistry(doc.clips, 'clips', issues, tryValidateClip)
      checkRegistry(doc.behaviors, 'behaviors', issues, tryValidateBehavior)
    },
  ])
}
