// ─────────────────────────────────────────────────────────────────────────────
// Drizzle schema for the notebook backend (Postgres). Every notebook save is a
// new `notebook_revisions` row; `notebook_current` is a singleton pointer to the
// live one — an audit trail with one-click rollback (see server/routes/notebook.ts).
//
// `invites` and `submissions` are defined here (schema-only, no routes yet) so
// step 4 of the plan (invite/submission backend) needs no new migration.
// Better Auth's own tables (users/sessions/accounts/passkeys) are generated by
// its Drizzle adapter in step 2 and will live alongside these.
// ─────────────────────────────────────────────────────────────────────────────
import { pgTable, serial, integer, text, jsonb, timestamp, check } from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'

// Better Auth's tables (user/session/account/verification/passkey), generated by
// `@better-auth/cli generate` (see server/auth.ts). Re-exported here so a single
// drizzle-kit `generate`/`migrate` covers both the app schema and auth tables,
// and so `db` (server/db/index.ts) knows the full schema.
export * from './auth-schema'

export const notebookRevisions = pgTable('notebook_revisions', {
  id: serial('id').primaryKey(),
  doc: jsonb('doc').notNull(),
  note: text('note'),
  createdBy: text('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const notebookCurrent = pgTable('notebook_current', {
  id: integer('id').primaryKey(),
  revisionId: integer('revision_id').notNull().references(() => notebookRevisions.id),
}, (table) => [
  check('notebook_current_singleton', sql`${table.id} = 1`),
])

// ── Invites (step 4: owner CRUD + public token lookup) ─────────────────────
export const invites = pgTable('invites', {
  id: serial('id').primaryKey(),
  token: text('token').notNull().unique(),
  label: text('label'),
  expiresAt: timestamp('expires_at', { withTimezone: true }),
  maxUses: integer('max_uses'),
  useCount: integer('use_count').notNull().default(0),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

// ── Submissions (step 4: public panel submissions via an invite) ───────────
export const submissions = pgTable('submissions', {
  id: serial('id').primaryKey(),
  inviteId: integer('invite_id').notNull().references(() => invites.id),
  authorName: text('author_name'),
  panel: jsonb('panel').notNull(),
  status: text('status', { enum: ['pending', 'approved', 'rejected'] }).notNull().default('pending'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
})
